/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stocktrader;

/**
 * Subclass of JPanel that holds an additional UserSystem attribute.
 * @author Shawn
 */
public class DisplayPanel extends javax.swing.JPanel {

    /**
     * Creates new form DisplayPanel
     */
    public DisplayPanel() {
        initComponents();
    }
    
    
    /**
     * Creates new form DisplayPanel. Provides value for userSystem attribute.
     * @param userSystem Initial value for userSystem.
     */
    public DisplayPanel(UserSystem userSystem) {
        userSys = userSystem;
        initComponents();
    }
    
    /**
     * Get the Current UserSystem.
     * @return Return the current UserSystem userSys.
     */
    public UserSystem getUserSystem() {
        return userSys;
    }
    
    
    /**
     * Set a new UserSystem.
     * @param newUserSys New UserSystem for the object.
     */
    public void setUserSystem(UserSystem newUserSys) {
        userSys = newUserSys;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    //UserSystem used to contain all users and current user.

    /**
     * userays 
     */
    protected UserSystem userSys = new UserSystem();
}

